### ISSUE TITLE
menu

### ISSUE THREAD

**Issue by Samuel20354** [aarav2you/Fish#7]
bro check ur code
![git fish](https://user-images.githubusercontent.com/68336568/111085638-17c9bc80-8510-11eb-9e0c-0cfe8c7e517b.png)
the logo and the redirect text is messed up!
and i did try to run the fishing site but that didn't work either 
error:
`  File "Sites/Outlook/app.py", line 28
    file.write(f"{list(data.keys())[0]} : {data[list(data.keys())[0]][0]}\n")
                                                                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/usr/local/bin/ngrok", line 5, in <module>
    from pyngrok.ngrok import main
ModuleNotFoundError: No module named 'pyngrok'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'int' object is not callable
`

**Comment by aarav2you** [comment]
The logo or the tagline will be printed out fine if the terminal is in full resolution. I am working on getting to dynamically adjust. I might have forgotten to mention currently ngrok only works for windows right now. What I suggest you do is open `fish.py` and delete the 2nd last line (above the end comment) then install [ngrok](https://ngrok.com) and run `ngrok http 5000` and select port 5000 or change accordingly in the script. I did not get what you mean redirect link is messed up, just press enter on all the options if you want default values

**Comment by aarav2you** [comment]
This is how it is supposed to look like if your terminal is full-screen, however, I am trying to shorten it. Might also not work if your resolution is less than 1980x1080

![image](https://user-images.githubusercontent.com/37036762/111099680-06ae9900-856c-11eb-8067-32590dca97f5.png)

**Comment by aarav2you** [comment]
Also please follow the template next time @Samuel20354

**Comment by Samuel20354** [comment]
thanks
